### ISSUE TITLE
3.4 Quick Start: Hello World LED Blinker Example

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#129]
**NOTE:** _This Subtask is linked to a larger Task List_ticket #120   

# **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

# **Objectives & Goals:**
  ### 1. How does this task relate to the value track(s)?
    - All of the effort we put into improving our product lines should provide value to our customers.
    - We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
        1. Development - 
        2. Deployment
        3. Production
This article helps users in the development stage so they can quickly learn how to run a basic application and start developing on a known good piece of code.

  ### 2. Create a short statement explaining the objectives and goals for this ticket.

The goal of this article is to:

- give a new user a starting point to create a new application 
- provide working code for a basic application that they can use to start building a more advanced solution with 

# **Reference Material:**
  ### 1. Provide hyperlinks for helpful and related information. 
Please refer to outline: 
https://docs.google.com/document/d/1h7JF9ceYgBxK7cVass_cCJOiFn6moJTYrZp7dWuJpKI/edit

# **Deliverables or Desired Outcome:**
  ### 1. What are the task owners expectations? 

- share links where to find the code to start using the Hello World LED Blinker demo application 

 ### 2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.
- a succinct article that follows our current style guide based on the original article
- based on this article, a new user should be able to load the example application, run it, modify and build their own code using the example LED Blinker code as a starting point. 

# **Date Required By:**
  ### 1. When is the scope required to be completed?
- no date has been specified 

 ### 2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
- Ticket #120  has a dependency on this ticket to be completed

**Comment by remingtontr** [comment]
Ready for initial review

**Comment by amsiotdeveloper** [comment]
@remingtontr  this is a good start.  Let's put this on hold until @greenbreakfast gets back and then he can support us with the required example code.

**Comment by remingtontr** [comment]
Okay, sounds good.

Tom Remington
________________________________

**Comment by greenbreakfast** [comment]
@remingtontr added comments and hello world code to the outline

**Comment by remingtontr** [comment]
I've revised the article based on your comments and added a background to the codeblock so it's easier to read in Google Docs.

**Comment by greenbreakfast** [comment]
@remingtontr added a few more comments

**Comment by greenbreakfast** [comment]
@remingtontr looks good, please go ahead with a PR
