### ISSUE TITLE
Use tabs in Quickstart article on serial command line for different operating system setup

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/documentation#157]
# What article does this bug/error affect?
*Provide either the URL or the path to the affected file*

docs/quickstart/serial-command-line.md

# **Describe the bug**
*A clear and concise description of what the bug/error or is.*

Currently this article has individual headers to describe the steps required for Windows, Mac, Linux:
<img width="836" alt="image" src="https://github.com/user-attachments/assets/d36aa0da-2733-423a-a230-d9f078d6873e">

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

A better UI for this would be tabs, similar to how the pinouts for the Omega2 vs Omega2S are displayed:
<img width="882" alt="image" src="https://github.com/user-attachments/assets/def41efb-86d3-432c-9c77-c36f1e93d904">

Code: 
https://github.com/OnionIoT/documentation/blob/main/docs/hardware-interfaces/pinouts.md?plain=1#L13-L24

Please update the serial command line quickstart article to use tabs

**Comment by remingtontr** [comment]
This change was done directly in the documentation code and a pull request created.
