### ISSUE TITLE
OPKG article should highlight the advanced topics

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/documentation#169]
# What article does this bug/error affect?

OPKG Package Manager (https://documentation.onioniot.com/packages/opkg-package-manager)
and 
Advanced Package Management (https://documentation.onioniot.com/packages/advanced-package-management)

# **Describe the issue**

The advanced package management article has useful information that is relevant to using the opkg package manager. However, users will need to "dig" in order to find the content in the advanced package management article.

# **Suggested Solution**

Add a section to the bottom of the OPKG Package Manager article. 

This section should:
- briefly mention there are advanced topics that fall outside of every day use of opkg
- give a one sentence overview of each of the two advanced topics
- link to the Advanced Package Management article for more information

**Comment by remingtontr** [comment]
I have made changes to the article in Google docs and updated the documentation map.

Ready for review.
