### ISSUE TITLE
Documentation Roadmap for OpenWRT Packages

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#25]
# **Task Owner:**
Who owns this task and will approve the final deliverables? 

Lazar

# **Objectives & Goals:**
  ### 1. How does this task relate to the value track(s)?
    - All of the effort we put into improving our product lines should provide value to our customers.
    - We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
        1. Development
        2. Deployment
        3. Production

- This is a task to plan the roadmap to develop a series articles to support the Development, Deployment, and Production efforts associated with packages.

  ### 2. Create a short statement explaining the objectives and goals for this ticket.

- Create an outline of articles that will be used to write about the topic of Packages.
     
# **Description of the Scope:**
  ### 1. Provide context while explaining the requirement of the ticket.

- Work on the google doc outline where Lazar created a brain dump.
https://docs.google.com/document/d/17y7IXmPv_IzLSVtd56pL5TW9qdCjOimJV8Zt9k9ehK4/edit

- Expand/modify the outline in the "The First Topic" section.  Currently there are approximately 5 articles outlined.
     - Analyze the current menu on the document site 
     https://documentation.onioniot.com/
     - Create suggested headings for each article and where they would go in the current menu 
     - The goal is to keep each article in the 500-800 word size.  Breakdown larger articles into 2 or more articles as needed to keep the word count down so the articles are succinct. 
     

  ### 2. Provide sketches and diagrams where possible.
- not required for this scope 

  ### 3. Add any other context or screenshots about the feature request here.

# **Reference Material:**
  ### 1. Provide hyperlinks for helpful and related information. 

# **Deliverables or Desired Outcome:**
  ### 1. What are the task owners expectations? 

  ### 2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

- Present an organized outline of articles to be written which address the users needs based around packages.

# **Date Required By:**
  ### 1. When is the scope required to be completed?

- Provide a draft by Dec 5 so everyone can review and prepare for the meeting scheduled on Dec 6. at 7:30MST 

  ### 2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.

- This is a hard date - meeting is scheduled specifically to review the plan.

**Comment by amsiotdeveloper** [comment]
The spreadsheet outline looks good, and well organized.

In our meeting on Dec 6, let's review the idea of having a glossary for each section of the menu.

There are a few good benefits to having a glossary in each section:
- it will define new terminology as the user goes down the roadmap learning.
- It should also make it a lot easier to find a definition for terms the user is not that familiar with as they read new articles.
- it will be a writing style that can be added to our style guide so the terminology declaration/definition task does not become a huge resource drain at this stage and it can be conquered one article at a time.

**Comment by iammuze** [comment]
Ready for the @amsiotdeveloper

**Comment by amsiotdeveloper** [comment]
@greenbreakfast I believe we can close this ticket now.  The spreadsheet @iammuze created will become a working document for the outline and he has pinned it in the documentation channel in slack for easy reference.
