### ISSUE TITLE
Task: Style Guide:

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#27]
# **Task Owner:**
Who owns this task and will approve the final deliverables? 

- Lazar

# **Objectives & Goals:**
  ### 1. How does this task relate to the value track(s)?
    - All of the effort we put into improving our product lines should provide value to our customers.
    - We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
        1. Development
        2. Deployment
        3. Production
- This task will help in all lanes of our value tracks. 
           
  ### 2. Create a short statement explaining the objectives and goals for this ticket.

A style guide will help us make consistent and professional looking documentation which will improve the overall user experience.  
     
# **Description of the Scope:**
  ### 1. Provide context while explaining the requirement of the ticket.

- Create a style guide for internal technical writers to create a consistent look on all our documentation.
- The style guide will also be shared publicly for other developers to make contributions using the same style. 
- Create a hyperlink to the style guide in the google doc:  Document Development process section 8
- Show examples of the styles we will standardize on
- The style guide will utilize Docusaurus guidelines where possible so please do not duplicate the Docusauraus style guide.  Provide reference links to Docusaurus where possible. 

  ### 2. Provide sketches and diagrams where possible.

  ### 3. Add any other context or screenshots about the feature request here.

# **Reference Material:**
  ### 1. Provide hyperlinks for helpful and related information. 

- A brief introduction to the style guide will be in our Document Development process section 8
https://docs.google.com/document/d/1YHRAMHztni5xu9dTDqMl4UGNbsAPPVjh/edit

# **Deliverables or Desired Outcome:**
  ### 1. What are the task owners expectations? 

The proposed location for the style guide would be to add it as an article in the document menu in the feedback and suggestions section to show users how they can contribute to the documentation: 

https://documentation.onioniot.com/feedback

  ### 2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

- A style guide article in the document menue
- Do not duplicate existing sylte guides in Docusaurus 
- Use existing style guides where possible 

# **Date Required By:**
  ### 1. When is the scope required to be completed?

No specified deadline, however it is recommended to complete this task priori to creating too many articles that might not follow the same style guidelines so we can avoid revising articles. 

  ### 2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
  no dependancies

**Comment by amsiotdeveloper** [comment]
@mh1412 as per our meeting yesterday, please ensure Mermaid gets added to the style guide for flow charts and diagrams.

**Comment by amsiotdeveloper** [comment]
From our meeting this morning:
@iammuze will include a section in the Style guide to outline a chapter:
- Introduction Article - providing a high level overview of the chapter.  The tone will target entry level and new users. 
- Subject Matter x.  The following articles will be targeting advanced users with specific technical content about the article concepts and/or how to guides etc. 
- Each chapter will have a glossary of terms.  This will include new terms introduced in this chapter, as well as acronyms.  Short 1-2 sentence definitions. 

Also specify Draw.io as our preferred tool or flow charts and diagrams. 
- create an naming convention for drawings so the files can be easily corelated with the document where it is used
- create a file management process how the drawings will be created, organized and managed in the repo so it is easy to maintain the source file and update documents with drawing revisions.

**Comment by amsiotdeveloper** [comment]
Please add to the style guide:

3rd person professional technical/business tone

**Comment by greenbreakfast** [comment]
@iammuze please add the current version of the style guide to the repo. You can add it to the top-level directory and name it `STYLE-GUIDE.md`

@amsiotdeveloper I think it makes sense to have the style guide in the GitHub repo (as opposed to published on documentation.onioniot.com) since anyone who plans to make changes to the documentation will need to visit/use this repo

**Comment by iammuze** [comment]
@greenbreakfast, @amsiotdeveloper  Yeah, Sure!
