### ISSUE TITLE
5.5.9 WiFi Antenna & u.FL connector

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#64]
**NOTE:** _This Subtask is linked to a larger Task List_ticket #44 

# **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

# **Objectives & Goals:**
  ### 1. How does this task relate to the value track(s)?
    - All of the effort we put into improving our product lines should provide value to our customers.
    - We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
        1. Development - The hardware chapter is important for evaluating the Omega modules for a new project and supporting developers in the development process.
        2. Deployment
        3. Production
           
  ### 2. Create a short statement explaining the objectives and goals for this ticket.

**Intro**
- The Omega2 has a built-in 2.4 GHz IEEE 802.11 b/g/n WiFi adapter
- An antenna is needed 

**Hardware**
- Omega2/2+
     - On-board antenna: ceramic surface-mount 2dBi directional chip antenna
     - U.FL connector for optional external antenna
          - Reuse content from https://docs.onion.io/omega2-docs/omega2p.html#the-u.fl-connector-1
     - Pinout diagram of Omega2 with Wifi antenna and u.fl connector highlighted
- Omega2S/Omega2S+
     - There is no built-in antenna on the Omega2S/2S+ module
     - The Omega2S supports on-board antennas as well as external antennas
          - On-board antennas, such as ceramic chip antennas or PCB trace antennas, need to be connected to the WiFi antenna pin
          - External antennas can be connected directly to the u.FL connector on the module
          - Note: only one of pin 24 or the u.FL connector should be used in a design. If both are connected to antennae, the transmission power will be split between the two.
     - Pinout diagram of Omega2S with Wifi antenna pin and u.fl connector highlighted

**Software**
- The open-source mt76 driver is used for wifi networking
- The Omega2 WiFi radio supports: 
     - Hosting an access point (AP)
     - Connecting to an existing wireless network (STA)
     - Hosting an access point and connecting to an existing wireless network simultaneously (AP+STA)
- Point to wifi networking article: https://documentation.onioniot.com/networking/wifi

# **Reference Material:**
  ### 1. Provide hyperlinks for helpful and related information. 

# **Deliverables or Desired Outcome:**
  ### 1. What are the task owners expectations? 

- Articles should be succinct, and minimalist.
- These are MVP articles, and we will expand on them as users provide feedback and requests.
- All articles from the Hardware chapter will go in the hardware branch. 

  ### 2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.
- a succinct article that follows our current style guide based on the original article

# **Date Required By:**
  ### 1. When is the scope required to be completed?
- no date has been specified 

### 2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
- Ticket #44 has a dependency on this ticket to be completed

**Comment by remingtontr** [comment]
Ready for initial review

**Comment by amsiotdeveloper** [comment]
@remingtontr  I did a bit of a larger revision on this article to help improve the tone and technical accuracy a little.
please review and revise accordingly.

**Comment by greenbreakfast** [comment]
Added comments and suggestions, please take a look @remingtontr and @amsiotdeveloper

**Comment by amsiotdeveloper** [comment]
@greenbreakfast @remingtontr this article is shaping up much better now - I like all the changes, however I'm confused about pin24.  Please see my comment in the draft article.

**Comment by greenbreakfast** [comment]
@amsiotdeveloper yep, we should stick with calling it the ANT pin. See my responses in the document.

**Comment by remingtontr** [comment]
Fixes and edits done, please review.

Tom Remington
________________________________

**Comment by greenbreakfast** [comment]
@remingtontr looking good, just one final question about the last suggestion. Good for PR after that

**Comment by greenbreakfast** [comment]
@remingtontr ready for PR
