### ISSUE TITLE
Update for SPI Article 

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#91]
# **Task Owner:**
Who owns this task and will approve the final deliverables? 

Lazar 

# **Objectives & Goals:**
  ### 1. How does this task relate to the value track(s)?
    - All of the effort we put into improving our product lines should provide value to our customers.
    - We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
        1. Development - this article is to help with development on Omega modules
        2. Deployment
        3. Production
           
  ### 2. Create a short statement explaining the objectives and goals for this ticket.
     
- a reboot is no longer required after installing the package for the new SPI device to be available so update the article accordingly
- Update the GPIO table

![SPI GPIO table](https://github.com/OnionIoT/documentation/assets/147923165/4aea36f7-63b0-4d57-aaf0-8d8c2a8e91ad)

# **Description of the Scope:**
  ### 1. Provide context while explaining the requirement of the ticket.
- update the original article to reflect the current changes 

  ### 2. Provide sketches and diagrams where possible.
see image above 

  ### 3. Add any other context or screenshots about the feature request here.

# **Reference Material:**
  ### 1. Provide hyperlinks for helpful and related information. 

Chapter 5.6.2 Software SPI Bus in the Omega Documentation Map
https://docs.google.com/spreadsheets/d/1fTDrf0dsUPS4fohyQdvlB0-9X2w-70VSxERb6fFvAFU/edit#gid=0

https://documentation.onioniot.com/device-tree-overlay/software-spi
https://docs.google.com/document/d/1PKIf4bKJXMCWQHgvZaSOVuvbAYOMKYOu/edit

# **Deliverables or Desired Outcome:**
  ### 1. What are the task owners expectations? 
- update the original article with the current content 
-
  ### 2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

# **Date Required By:**
  ### 1. When is the scope required to be completed?
- no specified date
- 
  ### 2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
- no dependencies

**Comment by greenbreakfast** [comment]
@remingtontr looks good, please go ahead with the PR
