### ISSUE TITLE
Introduction to Omega2

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#98]
**NOTE:** _This Subtask is linked to a larger Task List_ ticket #78 

# **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

# **Objectives & Goals:**
  ### 1. How does this task relate to the value track(s)?
    - All of the effort we put into improving our product lines should provide value to our customers.
    - We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
        1. Development
        2. Deployment
        3. Production
      This article is primarily targeting new users and prospective users.
           
  ### 2. Create a short statement explaining the objectives and goals for this ticket.
The objectives of this article is to provide an introduction to the Onion/Omega2 community so they can figure out the lay of the land and how to get involved.     

# **Description of the Scope:**

For the draft scope outline please refer to:

https://docs.google.com/document/d/1w67dYSW5Kp9E4u7liLximAxnMgJMtOyQrj-JYH162yc/edit

Anything in _italics_ is an instruction to the writer. The rest is content

Repurpose existing content where possible. 
- reuse content where possible
- create an article with a professional business/technical tone 
- create an article consistent with the style guide 

# **Reference Material:**
  ### 1. Provide hyperlinks for helpful and related information. 

Refer to the original article: https://docs.onion.io/omega2-docs/

# **Deliverables or Desired Outcome:**
  ### 1. What are the task owners expectations? 

The article should provide clear direction for a new user to get involved, and it should provide directions so they can find the appropriate content to answer more questions they may have. 

  ### 2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

working doc in google docs 
markdown pushed to repo 

# **Date Required By:**
  ### 1. When is the scope required to be completed?
no specified date 

  ### 2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
no dependencies

**Comment by remingtontr** [comment]
Ready for initial review. If someone can point me to the Introduction of new documentation on the community forum, I'll,add this to the article.

**Comment by amsiotdeveloper** [comment]
@remingtontr the introduction is just another chapter and it is intended to go here:
https://documentation.onioniot.com/

Good work!! First cut looks good to me!! 
Let's approve it and push it through unless @greenbreakfast has any last comments or suggestions?
